[build]
builder = "docker"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { NODE_ENV = "production", DATABASE_URL = "/app/data/sqlite.db" }